# Generated by Django 4.0.2 on 2022-02-10 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='rating',
            field=models.IntegerField(blank=0, default=0),
            preserve_default=False,
        ),
    ]
